import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
// import "./prosemirror.css";
import WorkspaceSwitcher from "@/ui/layout/workspace-switcher";
import UserDropdown from "@/ui/layout/user-dropdown";
import Settings from "@/ui/layout/settings";
import Divider from "@/ui/icons/divider";
import PageSwitcher from "@/ui/layout/page-switcher";
import Share from "@/ui/layout/share";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbPage,
  BreadcrumbSeparator,
  Toaster,
  Skeleton
} from "@repo/ui";
import Providers from "./providers";
import {Slash} from "lucide-react";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          <div className="px-5 w-full z-10 top-0 h-16 border-b border-gray-200 dark:border-zinc-800 bg-white/50 dark:bg-black/50 backdrop-blur-lg flex flex-row justify-between items-center">
            <Breadcrumb>
              <BreadcrumbList>
                <BreadcrumbItem>
                <Skeleton className="w-20 h-8 flex items-center justify-center mr-2">App name</Skeleton>
                  {/* <BreadcrumbLink href="/">Home</BreadcrumbLink> */}
                </BreadcrumbItem>
                <BreadcrumbSeparator>
                {/* <Slash className="text-stone-400"/> */}
                </BreadcrumbSeparator>
                <BreadcrumbItem>
                  <WorkspaceSwitcher />
                  {/* <BreadcrumbLink href="/components">Components</BreadcrumbLink> */}
                </BreadcrumbItem>
                <BreadcrumbSeparator>
                {/* <Slash className="text-stone-400"/> */}
                </BreadcrumbSeparator>
                <BreadcrumbItem>
                  <PageSwitcher />
                  {/* <BreadcrumbPage>Breadcrumb</BreadcrumbPage> */}
                </BreadcrumbItem>
              </BreadcrumbList>
            </Breadcrumb>
            {/* < */}
            {/* <div className="flex flex-row items-center">
              <div>website icon</div>
              <Divider className="ml-1" />
              <WorkspaceSwitcher />
              <Divider className="ml-1" />
              <PageSwitcher />
            </div> */}
            <div className="flex flex-row items-center justify-end">
              <Settings/>
              <Share className="mr-2" />
              <UserDropdown />
            </div>
          </div>
          <div className="h-[calc(100dvh-64px)] w-screen">{children}</div>
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
