import type { Metadata } from "next";
import localFont from "next/font/local";
import "../../globals.css";
import WorkspaceSwitcher from "@/ui/layout/workspace-switcher";
import UserDropdown from "@/ui/layout/user-dropdown";
import Settings from "@/ui/layout/settings";
import PageSwitcher from "@/ui/layout/page-switcher";
import Share from "@/ui/layout/share";
import PageTitleEditor from "@/ui/canvas/layout/page-title-editor";
import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbList,
  BreadcrumbSeparator,
  Toaster,
  Skeleton
} from "@repo/ui";
import Providers from "./providers";

// const roboto = Roboto({
//   subsets: ["latin"],
//   weight: ["300", "400", "700", "900"],
//   display: "swap",
// });

const geistSans = localFont({
  src: "../../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "../../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
          {/* <div className="sticky px-5 w-full z-10 top-0 h-12 border-b border-gray-200 dark:border-zinc-800 bg-white dark:bg-black/50 backdrop-blur-lg flex flex-row justify-between items-center"> */}
          {/* <div className="sticky px-5 w-full z-10 top-0 h-12 border-b border-gray-200 dark:border-zinc-800 bg-white dark:bg-black/50 backdrop-blur-lg flex flex-row justify-between items-center"> */}
          {/* <div className="sticky px-5 w-full z-10 top-0 h-14  bg-white dark:bg-black/50 backdrop-blur-lg flex flex-row justify-between items-center">
            <Breadcrumb className="basis-[40%]">
              <BreadcrumbList className="gap-0 sm:gap-0">
                <BreadcrumbItem>
                <Skeleton className="mx-2 w-20 h-8 flex items-center justify-center">App name</Skeleton>
                </BreadcrumbItem>
                <BreadcrumbSeparator>
                </BreadcrumbSeparator>
                <BreadcrumbItem>
                  <WorkspaceSwitcher />
                </BreadcrumbItem>
                <BreadcrumbSeparator>
                </BreadcrumbSeparator>
                <BreadcrumbItem>
                  <PageSwitcher />
                </BreadcrumbItem>
              </BreadcrumbList>
            </Breadcrumb>
            <div className="basis-[20%] flex items-center justify-center">
              <PageTitleEditor/>
            </div>
            <div className="basis-[40%] flex flex-row items-center justify-end">
              <Settings/>
              <Share className="mr-2" />
              <UserDropdown />
            </div>
          </div> */}
          {/* <div className="h-[calc(100dvh-48px)] w-screen">{children}</div> */}
          <div className="h-[calc(100dvh-56px)] w-screen">{children}</div>
          {/* <div className="h-[calc(100dvh - 64px)] w-screen">{children}</div> */}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
